### ISSUE TITLE
robot can't stand

### ISSUE THREAD

**Issue by inesying** [aCodeDog/legged-robots-manipulation#1]
I want to express my sincere gratitude for this open-sourcing project. I have been able to successfully run your pre-trained model, and the results are exceptional. However, when I attempt to train the model using your code without modifying any parameters, the outcome is quite strange. The robot seems unable to stand, and I am uncertain of the cause.

Has anyone encountered a similar issue? 
![image (2)](https://github.com/aCodeDog/legged-robots-manipulation/assets/44863485/038d445a-de1e-4914-81ae-194f48fe4dfd)

![image (1)](https://github.com/aCodeDog/legged-robots-manipulation/assets/44863485/0b274ec9-7712-4d57-8f4e-fbce20b2c082)

**Comment by aCodeDog** [comment]
I think you can a reward : default_joint_pos - joint_pos，that will work well
